### PR TITLE
UIDEXP-304: Need new permission(s) to view Data Export settings in UI

### PR DESCRIPTION
**Pull request by UladzislauKutarkin**
[UIDEXP-304](https://issues.folio.org/browse/UIDEXP-304)
Here we hide the action menu if user have only view permission. In prev implementation, we were disabling buttons in action menu.  All other implementation was done before in scope of that ticket

Can't make a video since perms not working locally.

### CODE REVIEW

**Comment by UladzislauKutarkin** [comment]
It's small changes to existing feature

**Review by vashjs — APPROVED** [review]

**Comment by UladzislauKutarkin** [comment]
Here we hide the action menu if user have only view permission. In prev implementation, we were disabling buttons in action menu

**Review by zburke — COMMENTED** [review]
Ah, I see: instead of hiding individual items on the Actions menu when a user lacks permission, we'll just hide the entire menu itself. 👌 

Somehow, sonarcloud is happy with this even though there doesn't appear to be a new test for it. Is it possible we have tests for visibility of individual menu-items, but not one for the visibility of the Action menu itself? Do you think we should?

**Comment by UladzislauKutarkin** [comment]
> Ah, I see: instead of hiding individual items on the Actions menu when a user lacks permission, we'll just hide the entire menu itself. 👌
> 
> Somehow, sonarcloud is happy with this even though there doesn't appear to be a new test for it. Is it possible we have tests for visibility of individual menu-items, but not one for the visibility of the Action menu itself? Do you think we should?

I wrote tests before. And I'm not sure that we can make it testable since we mock stripes core(including perms)

**Comment by zburke** [comment]
>  I'm not sure that we can make it testable

Previously, permissions were handled at the menu-item level, i.e. the Actions-menu is always visible but individual menu-items may be hidden). This implies tests must exist to determine the visibility of individual menu items. These tests should still work: if the entire menu is hidden, of course the menu-items are hidden too. 

Now, permissions are handled at the menu level, i.e. the Actions-menu itself may be hidden. This behavior is nicer: instead of showing a menu with no items, we just don't show the menu at all. We _should_ be able to test this functionality also/instead using the same logic: is the Actions menu itself hidden/visible based on this attribute?

**Pull request merged**
